services:
  av-parser-service:
    build: .
    tty: true                              # prevents OS from aggressively buffering stdout
    stdin_open: true                       # enables Docker log streaming to Portainer/Dozzle
    image: jhawk7/av-parser-service:arm64
    #image: jhawk7/av-parser-service:amd64
    container_name: av-parser-service
    ports:
      - "8888:8888"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - /mnt/media/media/Music:/app/audio_archive
      - /mnt/media/media/Videos:/app/video_archive
    restart: unless-stopped
  
  redis:
    image: "redis:alpine"
    command:
      - /bin/sh 
      - -c
      - redis-server --requirepass "$${REDIS_PASS:?REDIS_PASS not set}" --save 60 1 #save cmd for persistence
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    env_file:
      - .redis.env
    restart: unless-stopped
